// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
)

// ConfigGetParams is parameters of GET /config operation.
type ConfigGetParams struct {
	// Client application version (SemVer).
	AppVersion string
	// Client platform (e.g., android, ios).
	Platform string
}

func unpackConfigGetParams(packed middleware.Parameters) (params ConfigGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "appVersion",
			In:   "query",
		}
		params.AppVersion = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "platform",
			In:   "query",
		}
		params.Platform = packed[key].(string)
	}
	return params
}

func decodeConfigGetParams(args [0]string, argsEscaped bool, r *http.Request) (params ConfigGetParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: appVersion.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "appVersion",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.AppVersion = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "appVersion",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: platform.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "platform",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Platform = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "platform",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
