// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// ConfigGet implements GET /config operation.
//
// Get configuration for client.
//
// GET /config
func (UnimplementedHandler) ConfigGet(ctx context.Context, params ConfigGetParams) (r ConfigGetRes, _ error) {
	return r, ht.ErrNotImplemented
}
