openapi: 3.0.3
info:
  title: sw-config-api
  version: 1.0.0
  description: |
    The service returns configuration to the client depending on the version and platform.
    No authorization, no access checks.
paths:
  /config:
    get:
      summary: Get configuration for client
      parameters:
        - in: query
          name: appVersion
          schema:
            $ref: '#/components/schemas/SemVer'
          required: true
          description: Client application version (SemVer format MAJOR.MINOR.PATCH)
        - in: query
          name: platform
          schema:
            type: string
            example: android
          required: true
          description: Client platform (e.g., android, ios)
        - in: query
          name: assetsVersion
          schema:
            $ref: '#/components/schemas/SemVer'
          required: false
          description: Specific assets version (SemVer format MAJOR.MINOR.PATCH). If not provided, uses appVersion.
        - in: query
          name: definitionsVersion
          schema:
            $ref: '#/components/schemas/SemVer'
          required: false
          description: Specific definitions version (SemVer format MAJOR.MINOR.PATCH). If not provided, uses appVersion.
      responses:
        '200':
          description: Configuration found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Config'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        type: integer
                        example: 400
                      message:
                        type: string
                        example: "Missing required parameter: appVersion"
        '404':
          description: Configuration not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        type: integer
                        example: 404
                      message:
                        type: string
                        example: Configuration not found
components:
  schemas:
    SemVer:
      type: string
      pattern: '^\d+\.\d+\.\d+$'
      description: Semantic version in MAJOR.MINOR.PATCH format
      example: 13.6.956
    Config:
      type: object
      properties:
        version:
          $ref: '#/components/schemas/Version'
        backend_entry_point:
          $ref: '#/components/schemas/BackendService'
        assets:
          $ref: '#/components/schemas/Resource'
        definitions:
          $ref: '#/components/schemas/Resource'
        notifications:
          $ref: '#/components/schemas/BackendService'
    Version:
      type: object
      properties:
        required:
          $ref: '#/components/schemas/SemVer'
          description: Required version in SemVer format (MAJOR.MINOR.PATCH)
        store:
          $ref: '#/components/schemas/SemVer'
          description: Store version in SemVer format (MAJOR.MINOR.PATCH)
    BackendService:
      type: object
      properties:
        jsonrpc_url:
          type: string
          example: api.application.com/jsonrpc/v2
    Resource:
      type: object
      properties:
        version:
          $ref: '#/components/schemas/SemVer'
          description: Resource version in SemVer format (MAJOR.MINOR.PATCH)
        hash:
          type: string
          example: 0b313712189f60d9f46d36577140fb58beaec610353850f050cb897
        urls:
          type: array
          items:
            type: string
          example: [ "vqe.cdn.application.com", "wg.cdn.application.com" ]